# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Info
title:              Huy Nguyen's space
description:        A place you can have more information about me
logo_url:           https://avatars.githubusercontent.com/u/21701724?v=4 # Get it from GitHub API: https://api.github.com/users/<username>

# Author Info
author_name:        Huy Nguyen
email:              huynguyennhat@pm.me
twitter_username:   __huynguyen
github_username:    huynguyen-n

# Site Settings
url:                https://huy94.me
baseurl:            
permalink:          /:title
timezone:           Asia/Ho_Chi_Minh
mathjax:            true
social_share_previews: true

# Build Settings
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
exclude:            [ "README.md", "Gemfile" ]
plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
